# Path to the checkpoint file. Possible models are vit_h, vit_l and vit_b.
# checkpoint: "./checkpoints/sam_vit_h_4b8939.pth"
checkpoint: "/home/wsl/bin/segment-anything/checkpoints/sam_vit_h_4b8939.pth"
# Path to the output file.
output-directory: "./output"
# List of unique wing cell ids as they appear in the output file and their display names.
wing-cells:
  FWL: "forewing lobe"
  MC: "marginal cell"
  1sMC: "1st submarginal cell"
  2sMC: "2nd submarginal cell"
  3sMC: "3rd submarginal cell"
  1MdC: "1st medial cell"
  2MdC: "2nd medial cell"
  1CC: "1st cubital cell"
  2CC: "2nd cubital cell"
  RC: "radial cell"











